# Setup
title:               'Dr. James Howard'
tagline:             'A Mathematician, a Different Kind of Mathematician, and a Statistician'
description:         'A Mathematician, a Different Kind of Mathematician, and a Statistician'
url:                 'https://k3jph.github.io'
baseurl:             '/'

# About/contact
author:
  name:              'James P. Howard, II'
  url:               'https://jameshoward.us'
  email:             'jh@jameshoward.us'

# Gems
plugins:
  - jekyll-paginate
  - jekyll-redirect-from

# Pagination
paginate:            10
permalink:           pretty
paginate_path:       '/blog/page:num/'

# Custom vars
version:             1.1.0
google_analytics_id: UA-79581-8
