# Setup
title:               'Dr. James Howard'
tagline:             'A Mathematician, a Different Kind of Mathematician, and a Statistician'
description:         'A Mathematician, a Different Kind of Mathematician, and a Statistician'
url:                 ''
baseurl:             ''
twitter_username:    'k3jph'

# About/contact
author:
  name:              'James P. Howard, II'
  url:               'https://jameshoward.us'
  email:             'jh@jameshoward.us'

# Gems
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-scholar
  - jekyll/footnotes
  
# Pagination
paginate:            10
permalink:           pretty
paginate_path:       '/blog/page/:num/'

# Custom vars
version:             1.1.0
google_analytics_id: UA-79581-8

# Scholar settings
scholar:
  style: mla

# Iframely!
iframely-key:       176ff6184ababb980170f6037497fb6a